storage: /verdaccio/storage
plugins: /verdaccio/plugins

web:
  enable: false   # No web UI to reduce attack surface

listen:
  - 0.0.0.0:4873

uplinks:
  npmjs:
    url: https://registry.npmjs.org

packages:
  '@*/*':
    access: $all
    publish: nobody
    proxy: npmjs
  '**':
    access: $all
    publish: nobody
    proxy: npmjs

server:
  keepAliveTimeout: 60

logs: { type: stdout, format: pretty, level: info }
